### ISSUE TITLE
Last code version differs from the one at playshortfuse.com 

### ISSUE THREAD

**Issue by vjrabanelly** [cri5ti/html5-bomberman#1]
Hi!

I was digging the idea of creating an html5 bomberman with a friend this week and I found your very nice project when looking for existing ones in Github. I'm a web developer using all the technologies of your project already so it really comes in handy as a start for improvements.

Though, I noticed the code on your demo page playshortfuse.com is more up-to-date than the one in Github (which is actually buggy, the first thing I noticed was problem in the players moves). Could you commit the last version of your code please?

I'll then fork it and we'd be happy to bring improvements to the game with my friend!

Thanks!

**Comment by cri5ti** [comment]
Should be up to date now!
