### ISSUE TITLE
socket.io-client not loaded

### ISSUE THREAD

**Issue by djsb** [cri5ti/html5-bomberman#2]
Hi!

I was trying to setup html5-bomberman, but i'm getting an error on inspect element console saying that:

Uncaught Error: Module name 'socket.io-client' has not been loaded yet for context: _
http://requirejs.org/docs/errors.html#notloaded require-jquery.js:79
makeError require-jquery.js:79
context.require require-jquery.js:1358
requirejs require-jquery.js:1578
(anonymous function)

What could be wrong with this setup?

**Comment by tomas2387** [comment]
For anyone facing this issue I manage to silence the error changing the path to socket.io, _from_:

paths: {
   socketio: 'http://localhost/myapp/node_modules/socket.io/lib/socket.io'
},

_to_

paths: {
   socketio: 'http://localhost/myapp/node_modules/socket.io/node_modules/socket.io-client/dist/socket.io'
},

so now it points to the client version of socket.io not the main (server) version.
