### ISSUE TITLE
Lobby not working

### ISSUE THREAD

**Issue by jpgreth** [cri5ti/html5-bomberman#7]
When you open localhost:8080 (Lobby) there is a error "Uncaught ReferenceError: io is not defined".
What could be wrong there?

**Comment by cri5ti** [comment]
Seems like socket.io didn't load. 
Have a look in your network panel to see if socket.io.js loaded.

**Comment by jpgreth** [comment]
Ok, got it working. socket.io was loaded, but hat missing dependencies.
Had to copy `package.json` from `server/` to base dir and do a `sudo npm install`
